import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { RefineContext } from "./app-context";

export const metadata: Metadata = {
  title: "Demo",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const lang = cookieStore.get("NEXT_LOCALE");

  return (
    <html lang={lang?.value || "ja"}>
      <body>
        <Suspense>
            <RefineContext themeMode={theme?.value}>{children}</RefineContext>
        </Suspense>
      </body>
    </html>
  );
}
